#!/usr/bin/env ruby
#
# This pre-commit hook will execute a clean gradle build. An input is taken for
# the directory to run gradle in. It is then checked for any changes. If there
# are no changes the script exits 0. If changes are detected the tests are
# executed. If all tests pass it will exit 0.
#
require 'English'
require_relative '../lib/captain'

Captain.new('gradle')

Dir.chdir(Info.scriptDir)
@appDir = Info.getDir

Dir.chdir('../../') do
  case Info.findChanges(@appDir)
  when true
    Dir.chdir(@appDir) do
      Test.gradle('clean build test')
    end
    Info.success if $CHILD_STATUS.exitstatus.zero?
    exit $CHILD_STATUS.exitstatus
  else
    exit 0
  end
end
