#!/usr/bin/env ruby
#
# This pre-commit hook will execute a clean gradle build. An input is taken for
# the directory to run gradle in. It is then checked for any changes. If there
# are no changes the script exits 0. If changes are detected the tests are
# executed. If all tests pass it will exit 0.
#
require 'English'
require_relative '../lib/input'
require_relative '../lib/changes'
require_relative '../lib/success'
require_relative '../lib/test'

@test = 'gradle'

def getInput
  scriptDir = File.expand_path(File.dirname(__FILE__))
  Dir.chdir(scriptDir)

  @appDir = Input.getDir(@test)
end
getInput

def checkChanges
  Dir.chdir('../../') do
    gradleTest if Changes.findChanges(@appDir, @test)
  end
end
checkChanges

def gradleTest
  Dir.chdir('../../') do
    Dir.chdir(@appDir) do
      Test.gradle('clean build test')
    end
    Success.success(@test) if $CHILD_STATUS.exitstatus.zero?
    exit $CHILD_STATUS.exitstatus
  end
end
