#!/usr/bin/env ruby
#
# This pre-commit hook will execute a clean gradle build. An input is taken for
# the directory to run gradle in. It is then checked for any changes. If there
# are no changes the script exits 0. If changes are detected the tests are
# executed. If all tests pass it will exit 0.
#
require_relative '../lib/captain'

captain = Captain::Changes.new
logger = Captain::Logger.new

if captain.changed?
  #run test
  logger.info("Test Successful") #if things
else
  logger.info("No changes to test")
end
