#!/usr/bin/env ruby
#
# This will run a clean maven test. It is configured to run from the root of the
# project. If all tests pass it will exit 0.
#
require_relative '../lib/captain'

changes = Captain::Changes.new
logger = Captain::Logger.new


if changes.changed?
  Captain::Test.directory(changes.directory)
  Captain::Test.maven('clean', 'test')
  logger.info('Test Successful')
else
  logger.info('No changes to test')
end
