#!/usr/bin/env ruby
#
# This will run a clean maven test. It is configured to run from the root of the
# project. If all tests pass it will exit 0.
#
require 'English'
require_relative '../success'

def mavenTest
  scriptDir = File.expand_path(File.dirname(__FILE__))
  Dir.chdir(scriptDir)

  Dir.chdir('../../') do
    system('mvn clean test')
    Success.success('maven') if $CHILD_STATUS.exitstatus.zero?
    exit $CHILD_STATUS.exitstatus
  end
end
mavenTest
