#!/usr/bin/env ruby
#
# This pre-commit hook will execute a clean gradle build. An input is taken for
# the directory to run gradle in. It is then checked for any changes. If there
# are no changes the script exits 0. If changes are detected the tests are
# executed. If all tests pass it will exit 0.
#
require 'Engish'
require_relative '../lib/input'
require_relative '../lib/changes'
require_relative '../lib/success'
require_relative '../lib/test'
require_relative '../lib/scriptdir'

@test = 'rubocop'

Dir.chdir(Script.dir)
@appDir = Input.getDir(@test)

Dir.chdir('../../') do
  case Changes.findChanges(@appDir, @test)
  when true
    Dir.chdir(@appDir) do
      rubocopTest
    end
    Success.success(@test) if $CHILD_STATUS.exitstatus.zero?
    exit $CHILD_STATUS.exitstatus
  else
    exit 0
  end
end
