#!/usr/bin/env ruby

Dir.chdir(File.expand_path(File.dirname(__FILE__)))
Dir.chdir('../../')

properties = File.read('pipeline.properties')
increment = properties[/major$|minor$|patch$/]

puts "current version to increment is #{increment}"
print 'would you like to change this setting [y/n]: '
STDIN.reopen('/dev/tty')
choice = $stdin.gets.chomp
exit 0 if %w(no n).include?(choice.downcase)

puts 'increment values are major, minor, patch'
print 'version to increment: '
STDIN.reopen('/dev/tty')
version = $stdin.gets.chomp

new_increment = properties.gsub(/(major$|minor$|patch$)/, version)
File.open('pipeline.properties', 'w') { |file| file.puts new_increment }

system('git add pipeline.properties')
