#!/usr/bin/env ruby

require_relative '../lib/captain'

Captain::Version.get

puts "current version to increment is #{increment}"
print 'would you like to change this setting [y/n]: '
STDIN.reopen('/dev/tty')
choice = $stdin.gets.chomp
exit 0 if %w(no n).include?(choice.downcase)

puts 'increment values are major, minor, patch'
print 'version to increment: '
STDIN.reopen('/dev/tty')
version = $stdin.gets.chomp

Captain::Version.change(version)

system('git add pipeline.properties')
