#!/usr/bin/env ruby
#
# This script is used for the tagGitRepo Orion module. The pipeline.properties
# file will be parsed for the increment parameter's value and updated based on
# user input. The pipeline.properties file will then be added to the commit if
# the value has been changed.
#
require_relative '../lib/scriptdir'
require_relative '../lib/version'

Dir.chdir(Script.dir)
Increment.get('../../pipeline.properties')

puts 'acceptable increment values: [major, minor, patch]'
Increment.new

updateProperties unless Increment.validate

Increment.change('../../pipeline.properties')

Dir.chdir('../..') do
  system('git add pipeline.properties')
  exit 0
end
