#!/usr/bin/env ruby
#
# This script is used for the tagGitRepo Orion module. The pipeline.properties
# file will be parsed for the increment parameter's value and updated based on
# user input. The pipeline.properties file will then be added to the commit if
# the value has been changed.
#
require_relative '../lib/scriptdir'

def getIncrement
  Dir.chdir(Script.dir)
  Increment.get('../../pipeline.properties')
end
getIncrement

def newIncrement
  puts 'acceptable increment values: [major, minor, patch]'
  Increment.new
end
newIncrement

def validateIncrement
  updateProperties unless Increment.validate
end
validateIncrement

def updateProperties
  Increment.change('../../pipeline.properties')
end

def updateGit
  Dir.chdir('../..') do
    system('git add pipeline.properties')
    exit 0
  end
end
updateGit
