#!/usr/bin/env ruby
#
# This script takes an input for the directory to validate CFTs in. This
# directory is relative to the root of the project. If changes are detected it
# will execture the aws cli command for validating CFTs. If all validation
# passes it will exit 0. If no changes are detected it will exit 0
#
require 'English'
require_relative '../lib/captain'

changes = Captain::Changes.new
logger = Captain::Logger.new

if changes.changed?
  Captain::Test.directory(changes.directory)
  files = Dir.entries('.').reject { |f| File.directory? f }\
              .select { |i| i =~ /\.json|\.yaml|\.yml/ }

  print 'specify the profile for authentication: '
  STDIN.reopen('/dev/tty')
  profile = $stdin.gets.chomp

  files.each do |file|
    Captain::Test.cft(profile, file)
        break if $CHILD_STATUS.exitstatus != 0
  end
  logger.info('Test Successful')
else
  logger.info('No changes to test')
end
