#!/usr/bin/env ruby
#
# This script takes an input for the directory to validate CFTs in. This
# directory is relative to the root of the project. If changes are detected it
# will execture the aws cli command for validating CFTs. If all validation
# passes it will exit 0. If no changes are detected it will exit 0
#
require 'English'
require_relative '../lib/input'
require_relative '../lib/changes'
require_relative '../lib/success'
require_relative '../lib/test'
require_relative '../lib/scriptdir'

@test = 'CFT validation'

def getInput
  Dir.chdir(Script.dir)

  @appDir = Input.getDir(@test)
end

def checkChanges
  Dir.chdir('../../') do
    getAWSCreds if Changes.findChanges(@appDir, @test)
  end
end
checkChanges

def getAWSCreds
  print 'specify the profile for authentication: '
  STDIN.reopen('/dev/tty')
  @profile = $stdin.gets.chomp
end

def getCFT
  Dir.chdir(@cftDir) do
    @files = Dir.entries('.').reject { |f| File.directory? f }\
                .select { |i| i =~ /\.json|\.yaml|\.yml/ }
  end
end
getCFT

def validateCFT
  @files.each do |file|
    Test.cft(@profile, file)
    break if $CHILD_STATUS.exitstatus != 0
  end
  Success.success(@test) if $CHILD_STATUS.exitstatus.zero?
  exit $CHILD_STATUS.exitstatus
end
validateCFT
