#!/usr/bin/env ruby
#
# This script is used for the tagGitRepo Orion module. The pipeline.properties
# file will be parsed for the increment parameter's value and updated based on
# user input. The pipeline.properties file will then be added to the commit if
# the value has been changed.
#
def promptData()
	@properties = File.read('../../pipeline.properties')
	increment = @properties[/(major$|minor$|patch$)/]

	puts 'acceptable increment values: [major, minor, patch]'
	print "version to increment [#{increment}]: "
	STDIN.reopen('/dev/tty')
	@version = $stdin.gets.chomp

	if @version.eql?("")
		@version = increment
		puts 'keeping existing value'
		exit 0
	else
		puts "modifying value to #{@version}"
	end
end
promptData()

def updateProperties()
	newIncrement = @properties.gsub(/(major$|minor$|patch$)/, @version)

	File.open('../../pipeline.properties', 'w') { |file| file.puts newIncrement }
end
updateProperties()

def updateGit()
	Dir.chdir('../..') do
		system('git add pipeline.properties')
		exit 0
	end
end
updateGit()

