#!/usr/bin/env ruby
#
# This file is used to execute the pre-commit hooks. It calls the precommit task
# in the Rakefile which is located in the hooks directory at the root of the
# project.
#
require 'English'

def runRake
  scriptDir = File.expand_path(File.dirname(__FILE__))

  Dir.chdir(scriptDir) do
    Dir.chdir('../../hooks') do
      system('rake precommit')
      exit $CHILD_STATUS.exitstatus
    end
  end
end
runRake
