#!/usr/bin/ruby
#
# this script is used to validate the format of a commit message. The format is
# based on the best practice standards taught in the SSE Dojo and can be
# referenced in the SSE GitHub organization GitWorkshop project. If any part of
# the commit message does not conform you will be prompted to amend the commit.
#
require_relative '../lib/format'

editor = ENV['EDITOR'] != 'none' ? ENV['EDITOR'] : 'vim'
message_file = ARGV[0]

def check_format_rules(line_number, line)
  @real_line_number = line_number + 1
  @line_number = line_number
  @line = line

  Format.title_line(@line, @line_number, @real_line_number)
  Format.blank_line(@line, @line_number, @real_line_number)
  Format.line_chars(@line, @real_line_number)
end

loop do
  @commit_msg = []
  @errors = []

  Format.lines(message_file, @commit_msg, @errors)

  unless @errors.empty?
    Format.errors(message_file, @commit_msg, @errors)

    Format.fix(message_file, editor)
  end
  break
end
