#!/usr/bin/env ruby
#
# This script will append the exit status of all other hooks to the approved
# commit message.
#
require 'digest'
require_relative '../lib/prepare'

def getMessage
  @messageFile = ARGV[0]
  @originalMessage = File.read("../#{messageFile}")
  @hookStatus = File.read('/tmp/hookStatus')
end
getMessage

def prepSignature
  Prepare.signature(@hookStatus)
end
prepSignature

def formatMessage
  Prepare.message(@originalMessage)
end
formatMessage

def prepCommit
  Prepare.write(@originalMessage, @resultPosition, @hookStatus, @messageFile)
end
prepCommit
