#!/usr/bin/env ruby
#
# This script will append the exit status of all other hooks to the approved
# commit message.
#
require 'digest'
require_relative '../lib/prepare'

@messageFile = ARGV[0]
@originalMessage = File.read("../#{messageFile}")
@hookStatus = File.read('/tmp/hookStatus')

Prepare.signature(@hookStatus)
Prepare.message(@originalMessage)
Prepare.write(@originalMessage, @resultPosition, @hookStatus, @messageFile)
