# This file is called by any hooks being used in the .git/hooks directory. Each
# hook triggers the corresponding Rake task. The Rake task then will iterate
# through the corresponding directory and execute all hook scripts.
#
require 'English'

if Dir.exist?('pre-commit')
  task :precommit do
    FileList['pre-commit/*'].each do |file|
      system(file)
      next if $CHILD_STATUS.exitstatus.zero?
      exit $CHILD_STATUS.exitstatus unless $CHILD_STATUS.exitstatus.zero?
    end
  end
end

if Dir.exist?('commit-msg')
  task :commitmsg do
    ARGV.each { |i| task(i.to_sym) }
    FileList['commit-msg/*'].each do |file|
      cmd = "#{file} #{ARGV[1]}"
      system(cmd)
      next if $CHILD_STATUS.exitstatus.zero?
      exit $CHILD_STATUS.exitstatus unless $CHILD_STATUS.exitstatus.zero?
    end
  end
end

if Dir.exist?('prepare-commit-msg')
  task :preparecommitmsg do
    ARGV.each { |i| task(i.to_sym) }
    FileList['prepare-commit-msg/*'].each do |file|
      cmd = "#{file} #{ARGV[1]}"
      system(cmd)
      next if $CHILD_STATUS.exitstatus.zero?
      exit $CHILD_STATUS.exitstatus unless $CHILD_STATUS.exitstatus.zero?
    end
  end
end
