# This file is called by any hooks being used in the .git/hooks directory. Each
# hook triggers the corresponding Rake task. The Rake task then will iterate
# through the corresponding directory and execute all hook scripts.
#
if Dir.exists?('pre-commit')
	task :precommit do
		FileList['pre-commit/*'].each do |file|
			system(file)
			if $?.exitstatus == 0
				next
			else
				exit $?.exitstatus
			end
		end
	end
end

if Dir.exists?('commit-msg')
	task :commitmsg do
		ARGV.each { |i| task i.to_sym do ; end }
		FileList['commit-msg/*'].each do |file|
			cmd = "#{file} #{ARGV[1]}"
			system(cmd)
			if $?.exitstatus == 0
				next
			else
				exit $?.exitstatus
			end
		end
	end
end

if Dir.exists?('prepare-commit-msg')
	task :preparecommitmsg do
		ARGV.each { |i| task i.to_sym do ; end }
		FileList['prepare-commit-msg/*'].each do |file|
			cmd = "#{file} #{ARGV[1]}"
			system(cmd)
			if $?.exitstatus == 0
				next
			else
				exit $?.exitstatus
			end
		end
	end
end
